apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ws-client
  name: ws-client
spec:
  replicas: 1
  selector:
    name: ws-client
  template:
    metadata:
      labels:
        name: ws-client
    spec:
      containers:
        - image: kadle11/ws-sidecar:latest
          name: ws-client
          command: ["node", "webSocketClient.js", "ws-server:8080"]
          ports:
            - containerPort: 3000
              name: ws-client
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
      nodeSelector:
        kubernetes.io/hostname: node2
