apiVersion: v1
kind: Service
metadata:
  name: ws-server
  labels:
    name: ws-server
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: ws-server
  selector:
    name: ws-server
