apiVersion: v1
kind: Service
metadata:
  name: client-app
  labels:
    name: client-app
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: 7000
      # nodePort: 31500
      name: client-app
  selector:
    name: student-node-client
