apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  type: NodePort
  ports:
    - port: 7000
      targetPort: 7000
      nodePort: 31500
      name: app
  selector:
    name: student-node-client
