apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: student-node-client
  name: student-node-client
spec:
  replicas: 1
  selector:
    name: student-node-client
  template:
    metadata:
      labels:
        name: student-node-client
    spec:
      containers:
        - image: kadle11/student-node-app:latest
          name: student-node-app
          # command: ["node", "client.js", "app:3000"]
          command: ["node", "client.js", "ws-client:3000"]
          ports:
            - containerPort: 7000
              name: http-server
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
      nodeSelector:
        kubernetes.io/hostname: node2
