apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: student-node-app
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 25
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: student-node-app
