apiVersion: v1
kind: Service
metadata:
  name: student-database
  labels:
    name: student-database
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
      name: student-database
    - port: 7000
      targetPort: 7000
      nodePort: 32500
      name: grpc-server
  selector:
    name: web
