apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: kadle11/student-node-server:latest
        name: web
        ports:
        - containerPort: 3000
          name: http-server
        imagePullPolicy: Always
