apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: student-node-app
  name: student-node-app
spec:
  replicas: 1
  selector:
    name: student-node-app
  template:
    metadata:
      labels:
        name: student-node-app
    spec:
      containers:
      - image: kadle11/student-node-app:latest
        name: student-node-app
        command: ["node", "server.js", "mongo"]
        ports:
          - containerPort: 3000
            name: http-server
        imagePullPolicy: Always
      # Sidecar results in a failure to connect to MongoDB
      # Link: https://github.com/kubernetes/kubernetes/issues/61207
      # Fix: DNS Server Check - https://help.hcltechsw.com/connections/v6/admin/install/cp_prereq_kubernetes_dns.html
      - image: kadle11/ws-sidecar
        name: grpc-server
        command: ["node", "webSocketServer.js"]
        ports:
          - containerPort: 8080
            name: ws-server
        imagePullPolicy: Always      
      nodeSelector:
          id: worker1