apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: app
    # - port: 8080
    #   targetPort: 8080
    #   nodePort: 32500
    #   name: ws-server
  selector:
    name: student-node-app
